spring: 
  profiles:
    active: 
    - dev
---
spring: 
  profiles: dev     #开发--环境
  application: 
    name: microservice-cloud-config-bdqn-dev
---
spring: 
  profiles: test    #测试--环境
  application: 
    name: microservice-cloud-config-bdqn-test
